"""Add Profile & Connection updates

Revision ID: 23277a52dbb1
Revises: 
Create Date: 2025-11-22 14:05:27.282300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23277a52dbb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.create_unique_constraint('_user_target_uc', ['user_id', 'target_user_id'])
        batch_op.create_index('idx_target_user', ['target_user_id'], unique=False)

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=225),
               existing_nullable=True)
        batch_op.alter_column('interests',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('interests',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('profile_picture',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('bio',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('visibility')
        batch_op.drop_column('location')

    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.drop_index('idx_target_user')
        batch_op.drop_constraint('_user_target_uc', type_='unique')

    # ### end Alembic commands ###
