"""empty message

Revision ID: 97626838e30e
Revises: 13b40b854888
Create Date: 2025-12-28 20:25:41.030583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97626838e30e'
down_revision = '13b40b854888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vibe_daily_state',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_responses', sa.Integer(), nullable=True),
    sa.Column('dominant_choice', sa.Integer(), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('vibe_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('choice_index', sa.Integer(), nullable=False),
    sa.Column('anonymous_text', sa.String(length=80), nullable=True),
    sa.Column('vanish_count', sa.Integer(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['vibe_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'user_id', name='uq_vibe_vote_once')
    )
    with op.batch_alter_table('vibe_responses', schema=None) as batch_op:
        batch_op.create_index('ix_vibe_question_created', ['question_id', 'created_at'], unique=False)

    op.create_table('vibe_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['response_id'], ['vibe_responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'user_id', name='uq_vanish_once')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vibe_reports')
    with op.batch_alter_table('vibe_responses', schema=None) as batch_op:
        batch_op.drop_index('ix_vibe_question_created')

    op.drop_table('vibe_responses')
    op.drop_table('vibe_daily_state')
    # ### end Alembic commands ###
