"""recreate notifications with type and ref_id

Revision ID: b6e57af6e911
Revises: 43f834eae13b
Create Date: 2025-12-27 05:35:10.525625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e57af6e911'
down_revision = '43f834eae13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('ref_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notification_ref_id'), ['ref_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_ref_id'))
        batch_op.drop_column('ref_id')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
