"""empty message

Revision ID: e702c4d90481
Revises: 97626838e30e
Create Date: 2025-12-28 21:11:28.409238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e702c4d90481'
down_revision = '97626838e30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vibe_daily_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'vibe_questions', ['question_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vibe_daily_state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('question_id')

    # ### end Alembic commands ###
